---
abstract: 'approximate a number with a rational number'
author:
  - 'Diab Jerius  E<lt>djerius@cpan.orgE<gt>'
build_requires:
  Math::Trig: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.120921'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Rational-Approx
provides:
  Math::Rational::Approx:
    file: lib/Math/Rational/Approx.pm
    version: 0.02
  Math::Rational::Approx::ContFrac:
    file: lib/Math/Rational/Approx/ContFrac.pm
    version: 0.01
  Math::Rational::Approx::MaxD:
    file: lib/Math/Rational/Approx/MaxD.pm
    version: 0.01
requires:
  Moo: 0
  MooX::Types::MooseLike::Numeric: 0
  POSIX: 0
  Params::Validate: 0
resources:
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: https://bitbucket.org/djerius/math-rational-approx
version: 0.02
